#!/bin/bash
rm -rf CMake*
SOURCE_DIR=/lcrc/group/e3sm/soft/trilinos/source
INSTALL_DIR=/lcrc/group/e3sm/soft/trilinos/15.1.1/intel/20.0.4

BOOST_DIR=/lcrc/group/e3sm/soft/boost/1.83.0/intel/20.0.4
KOKKOS_DIR=/lcrc/group/e3sm/soft/kokkos/4.2.00/intel/20.0.4
NETCDF_DIR=/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/netcdf-c-4.4.1-a4hji6e
PNETCDF_DIR=/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/parallel-netcdf-1.11.0-icrpxty
HDF5_DIR=/gpfs/fs1/soft/chrysalis/spack/opt/spack/linux-centos8-x86_64/intel-20.0.4/hdf5-1.10.7-4cghwvq

cmake \
  -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_CXX_STANDARD=17 \
\
  -D CMAKE_C_COMPILER=${MPICC} \
  -D CMAKE_CXX_COMPILER=${MPICXX} \
  -D CMAKE_Fortran_COMPILER=${MPIF90} \
  -D CMAKE_C_FLAGS:STRING="" \
  -D CMAKE_CXX_FLAGS:STRING="" \
  -D CMAKE_Fortran_FLAGS:STRING="" \
  -D CMAKE_EXE_LINKER_FLAGS="" \
  -D CMAKE_SKIP_INSTALL_RPATH=TRUE \
\
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC=srun \
  -D MPI_EXEC_NUMPROCS_FLAG:STRING="-n" \
\
  -D TPL_ENABLE_SuperLU:BOOL=OFF \
  -D ML_ENABLE_SuperLU:BOOL=OFF \
  -D TPL_ENABLE_BLAS:BOOL=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_rt" \
  -D TPL_ENABLE_LAPACK:BOOL=ON \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_rt" \
\
  -D TPL_ENABLE_MKL=ON \
  -D MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
  -D MKL_LIBRARY_NAMES:STRING="mkl_rt" \
  -D MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" \
\
  -D TPL_ENABLE_PARDISO_MKL:BOOL=ON \
  -D PARDISO_MKL_LIBRARY_DIRS:FILEPATH="${MKLROOT}/lib/intel64" \
  -D PARDISO_MKL_LIBRARY_NAMES:STRING="mkl_rt" \
  -D PARDISO_MKL_INCLUDE_DIRS:FILEPATH="${MKLROOT}/include" \
\
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=${BOOST_DIR}/include \
\
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D Netcdf_INCLUDE_DIRS:PATH=${NETCDF_DIR}/include \
  -D Netcdf_LIBRARY_DIRS:PATH=${NETCDF_DIR}/lib \
  -D TPL_Netcdf_PARALLEL:BOOL=ON \
\
  -D TPL_ENABLE_Pnetcdf:STRING=ON \
  -D Pnetcdf_INCLUDE_DIRS:PATH=${PNETCDF_DIR}/include \
  -D Pnetcdf_LIBRARY_DIRS:PATH=${PNETCDF_DIR}/lib \
\
  -D TPL_ENABLE_HDF5:STRING=ON \
  -D HDF5_INCLUDE_DIRS:PATH=${HDF5_DIR}/include \
  -D HDF5_LIBRARY_DIRS:PATH=${HDF5_DIR}/lib\
\
  -D TPL_ENABLE_Kokkos:BOOL=ON \
  -D Kokkos_ROOT=${KOKKOS_DIR}/lib64/cmake/Kokkos \
\
  -D Trilinos_ASSERT_DEFINED_DEPENDENCIES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_CXX11:BOOL=ON \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
  -D Trilinos_ENABLE_Fortran:BOOL=ON \
  -D Trilinos_ENABLE_SHADOW_WARNINGS=OFF \
  -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
  -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
\
  -D Amesos2_ENABLE_KLU2:BOOL=ON \
  -D Intrepid_ENABLE_TESTS:BOOL=OFF \
  -D Intrepid2_ENABLE_TESTS:BOOL=OFF \
  -D Phalanx_INDEX_SIZE_TYPE:STRING="INT" \
  -D Phalanx_KOKKOS_DEVICE_TYPE:STRING="SERIAL" \
  -D Phalanx_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
  -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
  -D Tpetra_INST_INT_INT:BOOL=OFF \
  -D Tpetra_IGNORE_KOKKOS_COMPATIBILITY:BOOL=ON \
  -D Zoltan_ENABLE_ULONG_IDS:BOOL=ON \
\
  -D TPL_ENABLE_Matio:BOOL=OFF \
  -D TPL_ENABLE_X11:BOOL=OFF \
\
  -D Trilinos_ENABLE_Amesos2:BOOL=ON \
  -D Trilinos_ENABLE_Anasazi:BOOL=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
  -D Trilinos_ENABLE_Epetra:BOOL=OFF \
  -D Trilinos_ENABLE_EpetraExt:BOOL=OFF \
  -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
  -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
  -D Trilinos_ENABLE_Kokkos:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=ON \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
  -D Trilinos_ENABLE_Pamgen:BOOL=ON \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Trilinos_ENABLE_Piro:BOOL=ON \
  -D Trilinos_ENABLE_ROL:BOOL=ON \
  -D Trilinos_ENABLE_SEACASExodus:BOOL=ON \
  -D Trilinos_ENABLE_SEACASAprepro_lib:BOOL=ON \
  -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
  -D Trilinos_ENABLE_SEACASEpu:BOOL=ON \
  -D Trilinos_ENABLE_SEACASExodiff:BOOL=ON \
  -D Trilinos_ENABLE_SEACASNemslice:BOOL=ON \
  -D Trilinos_ENABLE_SEACASNemspread:BOOL=ON \
  -D Trilinos_ENABLE_STKDoc_tests:BOOL=OFF \
  -D Trilinos_ENABLE_STKIO:BOOL=ON \
  -D Trilinos_ENABLE_STKMesh:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_Teko:BOOL=ON \
  -D Trilinos_ENABLE_Tempus:BOOL=ON \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Thyra:BOOL=ON \
  -D Trilinos_ENABLE_ThyraTpetraAdapters:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
\
  -D TPL_FIND_SHARED_LIBS:BOOL=ON \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_LINK_SEARCH_START_STATIC:BOOL=OFF \
\
  -D Trilinos_ENABLE_PanzerDofMgr:BOOL=ON \
  -D Trilinos_ENABLE_PanzerExprEval:BOOL=ON \
  -D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=ON \
\
  ${SOURCE_DIR}
